name: CI for VPN Bot

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker images
        run: docker compose build

      - name: Run Docker containers
        run: docker compose up -d

      # Пример: запустить тест (если есть)
      # - name: Run tests
      #   run: docker compose exec bot python -m unittest discover

      - name: Stop Docker containers
        run: docker compose down

#Добавлен CI на GitHub Actions
